create stringBinarySearch.py
ShubhKotnala/Data_Structures_And_Algorithms pull request #58
Opened 2022-10-15 16:41 UTC by Mr-okey

### Checklist
🚨 Please review this repository's [contribution guidelines](./CONTRIBUTIONS.md).

- [ ] I've read and agree to the project's contribution guidelines.
- [ ] I'm requesting to **pull a topic/feature/bugfix branch**.
- [ ] I checked that my code additions will pass code linting checks and tests.
- [ ] I have added a comment block to support my contribution

### Description
What does this change do and why?

Thank you!

2022-10-15 16:46 UTC, ShubhKotnala requested changes
This code doesn't have a driver method, instead it would run directly. 
Can we break it down into modules, and introduce a main method which would have our test cases?

2022-10-15 16:46 UTC, ShubhKotnala commented on python/searching/StringBinarySearch.py
> +# function to decide the flow of search
Can you add a comment block explaining what is String Binary Search, along with some test cases, which would then be validated by this code block

2022-10-15 18:54 UTC, Mr-okey commented
Added comments for better understanding of algorithm.

2022-10-16 16:24 UTC, ShubhKotnala approved these changes

2022-10-16 16:24 UTC, merged